import { RequiredEntityData } from "@mikro-orm/core";
import {
  vehicleDroneTypeEnum,
  restrictionEnum,
  groundcraftSubtypeEnum,
  watercraftSubtypeEnum,
  aircraftSubtypeEnum,
  droneSubtypeEnum,
} from "@shadowrun/common";
import {
  Groundcrafts,
  Watercrafts,
  Aircrafts,
  Drones,
} from "../../../../../src/models/gear/riggerGear/vehicleAndDroneModel.js";

export const groundcraftsList: Array<RequiredEntityData<Groundcrafts>> = [
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Bikes,
    name: "Dodge Scoot",
    handling: [4, 3],
    speed: [3],
    acceleration: 1,
    body: 4,
    armour: 4,
    pilot: 1,
    sensor: 1,
    seats: 1,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 3000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Bikes,
    name: "Harley-Davidson Scorpion",
    handling: [4, 3],
    speed: [4],
    acceleration: 2,
    body: 8,
    armour: 9,
    pilot: 1,
    sensor: 2,
    seats: 1,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 12000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Bikes,
    name: "Yamaha Growler",
    handling: [4, 5],
    speed: [3, 4],
    acceleration: 1,
    body: 5,
    armour: 5,
    pilot: 1,
    sensor: 1,
    seats: 1,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 5000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Bikes,
    name: "Suzuki Mirage",
    handling: [5, 3],
    speed: [6],
    acceleration: 3,
    body: 5,
    armour: 6,
    pilot: 1,
    sensor: 2,
    seats: 1,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 8500 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Cars,
    name: "Chrysler-Nissan Jackrabbit",
    handling: [4, 3],
    speed: [3],
    acceleration: 2,
    body: 8,
    armour: 4,
    pilot: 1,
    sensor: 2,
    seats: 2,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 10000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Cars,
    name: "Honda Spirit",
    handling: [3, 2],
    speed: [4],
    acceleration: 2,
    body: 8,
    armour: 6,
    pilot: 2,
    sensor: 3,
    seats: 3,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 12000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Cars,
    name: "Hyundai Shin-Hyung",
    handling: [5, 4],
    speed: [6],
    acceleration: 3,
    body: 10,
    armour: 6,
    pilot: 1,
    sensor: 2,
    seats: 4,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 28500 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Cars,
    name: "Eurocar Westwind 3000",
    handling: [6, 4],
    speed: [7],
    acceleration: 3,
    body: 10,
    armour: 8,
    pilot: 3,
    sensor: 5,
    seats: 2,
    availability: {
      rating: 13,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 110000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Cars,
    name: "Ford Americar",
    handling: [4, 3],
    speed: [3],
    acceleration: 2,
    body: 11,
    armour: 6,
    pilot: 1,
    sensor: 2,
    seats: 4,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 16000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Cars,
    name: "Saeder-Krupp-Bentley Concordat",
    handling: [5, 4],
    speed: [5],
    acceleration: 2,
    body: 12,
    armour: 12,
    pilot: 2,
    sensor: 4,
    seats: 4,
    availability: {
      rating: 10,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 65000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.Cars,
    name: "Mitsubishi Nightsky",
    handling: [4, 3],
    speed: [4],
    acceleration: 2,
    body: 15,
    armour: 15,
    pilot: 3,
    sensor: 5,
    seats: 8,
    availability: {
      rating: 16,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 320000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.TrucksAndVans,
    name: "Toyota Gopher",
    handling: [5, 5],
    speed: [4],
    acceleration: 2,
    body: 14,
    armour: 10,
    pilot: 1,
    sensor: 2,
    seats: 3,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 25000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.TrucksAndVans,
    name: "GMC Bulldog",
    handling: [3, 3],
    speed: [3],
    acceleration: 1,
    body: 16,
    armour: 12,
    pilot: 1,
    sensor: 2,
    seats: 6,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 35000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.TrucksAndVans,
    name: "Rover Model 2072",
    handling: [5, 5],
    speed: [4],
    acceleration: 2,
    body: 15,
    armour: 12,
    pilot: 2,
    sensor: 4,
    seats: 6,
    availability: {
      rating: 10,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 68000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Groundcrafts,
    subtype: groundcraftSubtypeEnum.TrucksAndVans,
    name: "Ares Roadmaster",
    handling: [3, 3],
    speed: [3],
    acceleration: 1,
    body: 18,
    armour: 18,
    pilot: 3,
    sensor: 3,
    seats: 8,
    availability: {
      rating: 8,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 52000 },
    description: "",
  },
];

export const watercraftsList: Array<RequiredEntityData<Watercrafts>> = [
  {
    type: vehicleDroneTypeEnum.Watercrafts,
    subtype: watercraftSubtypeEnum.Boats,
    name: "Samuvani Otter",
    handling: [4],
    speed: [3],
    acceleration: 2,
    body: 12,
    armour: 6,
    pilot: 2,
    sensor: 2,
    seats: 8,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 21000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Watercrafts,
    subtype: watercraftSubtypeEnum.Boats,
    name: "Yongkang Gala Trinity",
    handling: [5],
    speed: [6],
    acceleration: 3,
    body: 10,
    armour: 6,
    pilot: 1,
    sensor: 1,
    seats: 3,
    availability: {
      rating: 8,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 37000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Watercrafts,
    subtype: watercraftSubtypeEnum.Boats,
    name: "Morgan Cutlass",
    handling: [5],
    speed: [4],
    acceleration: 2,
    body: 16,
    armour: 10,
    pilot: 3,
    sensor: 5,
    seats: 6,
    availability: {
      rating: 14,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 96000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Watercrafts,
    subtype: watercraftSubtypeEnum.Submarines,
    name: "Proteus Lamprey",
    handling: [3],
    speed: [2],
    acceleration: 1,
    body: 6,
    armour: 6,
    pilot: 1,
    sensor: 3,
    seats: 4,
    availability: {
      rating: 0,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 14000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Watercrafts,
    subtype: watercraftSubtypeEnum.Submarines,
    name: "Vulkan Electronaut",
    handling: [3],
    speed: [3],
    acceleration: 1,
    body: 12,
    armour: 10,
    pilot: 4,
    sensor: 4,
    seats: 2,
    availability: {
      rating: 10,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 108000 },
    description: "",
  },
];

export const aircraftsList: Array<RequiredEntityData<Aircrafts>> = [
  {
    type: vehicleDroneTypeEnum.Aircrafts,
    subtype: aircraftSubtypeEnum.FixedWingAircrafts,
    name: "Artemis Nightwing",
    handling: [6],
    speed: [3],
    acceleration: 1,
    body: 4,
    armour: 0,
    pilot: 1,
    sensor: 1,
    seats: 1,
    availability: {
      rating: 8,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 20000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Aircrafts,
    subtype: aircraftSubtypeEnum.FixedWingAircrafts,
    name: "Cessna C750",
    handling: [3],
    speed: [5],
    acceleration: 3,
    body: 18,
    armour: 4,
    pilot: 2,
    sensor: 2,
    seats: 4,
    availability: {
      rating: 8,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 148000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Aircrafts,
    subtype: aircraftSubtypeEnum.FixedWingAircrafts,
    name: "Renault-Fiat Fokker Tundra-9",
    handling: [3],
    speed: [4],
    acceleration: 3,
    body: 20,
    armour: 10,
    pilot: 3,
    sensor: 3,
    seats: 24,
    availability: {
      rating: 12,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 300000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Aircrafts,
    subtype: aircraftSubtypeEnum.Rotorcrafts,
    name: "Ares Dragon",
    handling: [4],
    speed: [4],
    acceleration: 3,
    body: 22,
    armour: 8,
    pilot: 3,
    sensor: 3,
    seats: 18,
    availability: {
      rating: 12,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 355000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Aircrafts,
    subtype: aircraftSubtypeEnum.Rotorcrafts,
    name: "Nissan Hound",
    handling: [5],
    speed: [4],
    acceleration: 3,
    body: 16,
    armour: 16,
    pilot: 2,
    sensor: 4,
    seats: 12,
    availability: {
      rating: 13,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 425000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Aircrafts,
    subtype: aircraftSubtypeEnum.Rotorcrafts,
    name: "Northrup Wasp",
    handling: [5],
    speed: [5],
    acceleration: 3,
    body: 10,
    armour: 8,
    pilot: 3,
    sensor: 3,
    seats: 1,
    availability: {
      rating: 12,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 86000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Aircrafts,
    subtype: aircraftSubtypeEnum.VTOL_VSTOLs,
    name: "Ares Venture",
    handling: [5],
    speed: [7],
    acceleration: 4,
    body: 16,
    armour: 14,
    pilot: 4,
    sensor: 4,
    seats: 6,
    availability: {
      rating: 12,
      restriction: restrictionEnum.Forbidden,
    },
    cost: { base: 400000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Aircrafts,
    subtype: aircraftSubtypeEnum.VTOL_VSTOLs,
    name: "GMC Banshee",
    handling: [6],
    speed: [8],
    acceleration: 4,
    body: 20,
    armour: 18,
    pilot: 4,
    sensor: 6,
    seats: 12,
    availability: {
      rating: 24,
      restriction: restrictionEnum.Forbidden,
    },
    cost: { base: 2500000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Aircrafts,
    subtype: aircraftSubtypeEnum.VTOL_VSTOLs,
    name: "Federated Boeing Commuter",
    handling: [3],
    speed: [3],
    acceleration: 3,
    body: 16,
    armour: 8,
    pilot: 3,
    sensor: 3,
    seats: 30,
    availability: {
      rating: 10,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 350000 },
    description: "",
  },
];

export const dronesList: Array<RequiredEntityData<Drones>> = [
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.Microdrones,
    name: "Shiawase Kanmushi",
    handling: [4],
    speed: [2],
    acceleration: 1,
    body: 0,
    armour: 0,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 8,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 1000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.Microdrones,
    name: "Sikorsky-Bell Microskimmer",
    handling: [3],
    speed: [3],
    acceleration: 1,
    body: 0,
    armour: 0,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 6,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 1000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.Minidrones,
    name: "Horizon Flying Eye",
    handling: [4],
    speed: [3],
    acceleration: 2,
    body: 1,
    armour: 0,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 8,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 2000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.Minidrones,
    name: "MCT Fly-Spy",
    handling: [4],
    speed: [3],
    acceleration: 2,
    body: 1,
    armour: 0,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 8,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 2000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.SmallDrones,
    name: "Aztechnology Crawler",
    handling: [4],
    speed: [3],
    acceleration: 1,
    body: 3,
    armour: 3,
    pilot: 4,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 4,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 4000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.SmallDrones,
    name: "Lockheed Optic-X2",
    handling: [4],
    speed: [4],
    acceleration: 3,
    body: 2,
    armour: 2,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 10,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 21000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.MediumDrones,
    name: "Ares Duelist",
    handling: [3],
    speed: [3],
    acceleration: 1,
    body: 4,
    armour: 4,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 5,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 4500 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.MediumDrones,
    name: "GM-Nissan Doberman",
    handling: [5],
    speed: [3],
    acceleration: 1,
    body: 4,
    armour: 4,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 4,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 5000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.MediumDrones,
    name: "MCT-Nissan Roto-Drone",
    handling: [4],
    speed: [4],
    acceleration: 2,
    body: 4,
    armour: 4,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 6,
      restriction: restrictionEnum.Legal,
    },
    cost: { base: 5000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.LargeDrones,
    name: "Cyberspace Designs Dalmatian",
    handling: [5],
    speed: [5],
    acceleration: 3,
    body: 5,
    armour: 5,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 6,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 10000 },
    description: "",
  },
  {
    type: vehicleDroneTypeEnum.Drones,
    subtype: droneSubtypeEnum.LargeDrones,
    name: "Steel Lynx",
    handling: [5],
    speed: [4],
    acceleration: 2,
    body: 6,
    armour: 12,
    pilot: 3,
    sensor: 3,
    seats: 0,
    availability: {
      rating: 10,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 25000 },
    description: "",
  },
];
