import { RequiredEntityData } from "@mikro-orm/core";
import {
  MeleeWeapons,
  ProjectileWeapons,
  FirearmWeapons,
  Explosives,
} from "../../../../../src/models/gear/combatGear/weaponModel.js";
import {
  skillsEnum,
  weaponTypeEnum,
  meleeWeaponTypeEnum,
  damageCalculationMethodEnum,
  damageTypeEnum,
  restrictionEnum,
  projectileWeaponTypeEnum,
  damageAnnoationEnum,
  firearmModeEnum,
  firearmWeaponTypeEnum,
  reloadMethodEnum,
  mathOperatorEnum,
  explosiveTypeEnum,
} from "@shadowrun/common";

export const meleeWeaponsList: Array<RequiredEntityData<MeleeWeapons>> = [
  {
    id: "ad4a06e3-7f8e-4f05-a42e-5be2c875bb72",
    name: "Ares 'One' Monosword",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "6",
    accuracy: "5",
    reach: "1",
    damage: "(STR+3)P",
    armourPenetration: "-3",

    availability: "8R",
    cost: "900",
    allowaccessory: true,
    source: "RG",
    page: "19",
  },
  {
    id: "7c59cf2f-87ea-4dca-95e7-ad17008386a0",
    name: "Combat Axe",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Axes",
    conceal: "10",
    accuracy: "4",
    reach: "2",
    damage: "(STR+5)P",
    armourPenetration: "-4",

    availability: "12R",
    cost: "4000",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "656906d8-b6a4-47a2-9554-de365097eba0",
    name: "Combat Knife",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Knives",
    conceal: "-2",
    accuracy: "6",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-3",

    availability: "4",
    cost: "300",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "78bcb170-2292-4f90-af26-dd16ff303569",
    name: "Cougar Fineblade: Long",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "2",
    accuracy: "7",
    reach: "0",
    damage: "(STR+3)P",
    armourPenetration: "-1",

    availability: "7R",
    cost: "600",
    allowaccessory: true,
    source: "RG",
    page: "20",
  },
  {
    id: "bb068078-540d-4c98-85fd-e526e381dec9",
    name: "Cougar Fineblade: Short",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "0",
    accuracy: "7",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-1",

    availability: "5R",
    cost: "350",
    allowaccessory: true,
    source: "RG",
    page: "20",
  },
  {
    id: "4ca64aa3-f172-4f0b-8c6d-954ddd1133b1",
    name: "Forearm Snap-Blades",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    conceal: "-2",
    accuracy: "4",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-2",

    availability: "7R",
    cost: "200",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "5ec246dc-c129-4e61-a27a-c4d82b223bea",
    name: "Hand Blade",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Cyber Implants",
    conceal: "-2",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-2",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "SR5",
    page: "458",
  },
  {
    id: "16fe95d3-9c66-4ac6-b4e3-562de5e5619e",
    name: "Hand Razors",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Cyber Implants",
    conceal: "-2",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-3",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "SR5",
    page: "458",
  },
  {
    id: "cae4ffe9-cf22-4917-92b1-57be89741f07",
    name: "Highland Forge Claymore",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "10",
    accuracy: "5",
    reach: "2",
    damage: "(STR+5)P",
    armourPenetration: "-5",

    availability: "14R",
    cost: "4500",
    allowaccessory: true,
    source: "RG",
    page: "18",
  },
  {
    id: "2ac6ad2e-1252-4204-943e-7b65ffbe803f",
    name: "Horizon-Flynn Rapier",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "4",
    accuracy: "7",
    reach: "1",
    damage: "(STR+2)P",
    armourPenetration: "-3",

    availability: "9R",
    cost: "500",
    allowaccessory: true,
    source: "RG",
    page: "18",
  },
  {
    id: "8f266b4c-4035-4ba3-aa89-3289d0f42ce1",
    name: "Katana",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "6",
    accuracy: "7",
    reach: "1",
    damage: "(STR+3)P",
    armourPenetration: "-3",

    availability: "9R",
    cost: "1000",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "eb16de72-e646-4880-aa5b-21a5a0a2b342",
    name: "Knife",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Knives",
    conceal: "-2",
    accuracy: "5",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-1",

    availability: "0",
    cost: "10",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "60f52b1f-6376-49fc-a746-b811c54197e7",
    name: "Pole Arm",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    conceal: "10",
    accuracy: "5",
    reach: "3",
    damage: "(STR+3)P",
    armourPenetration: "-2",

    availability: "6R",
    cost: "1000",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "fe835c72-a973-4976-bf5f-751aff1371d4",
    name: "Spurs",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Cyber Implants",
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+3)P",
    armourPenetration: "-2",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "SR5",
    page: "458",
  },
  {
    id: "e5e5e025-8622-406c-a2bb-030ad5392d79",
    name: "Survival Knife",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Knives",
    conceal: "-2",
    accuracy: "5",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-1",

    availability: "0",
    cost: "100",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "95fd2fb9-f174-4f03-add9-80e1d947bd5b",
    name: "Sword",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "4",
    accuracy: "6",
    reach: "1",
    damage: "(STR+3)P",
    armourPenetration: "-2",

    availability: "5R",
    cost: "500",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "dd817517-aa02-4035-9a3c-c0274f705822",
    name: "Victorinox Memory Blade: Dagger",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "-2",
    accuracy: "5",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-2",

    availability: "14R",
    cost: "1250",
    allowaccessory: true,
    source: "RG",
    page: "19",
  },
  {
    id: "47cb2812-b8dd-4f6d-8671-0f2736f29124",
    name: "Victorinox Memory Blade: Sword",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "4",
    accuracy: "5",
    reach: "1",
    damage: "(STR+2)P",
    armourPenetration: "-2",

    availability: "14R",
    cost: "1500",
    allowaccessory: true,
    source: "RG",
    page: "19",
  },
  {
    id: "5af85697-7d67-4bf7-b539-dbd4e63a34d1",
    name: "Club",
    category: meleeWeaponTypeEnum.Club,
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "4",
    reach: "1",
    damage: "(STR+3)P",
    armourPenetration: "-",

    availability: "0",
    cost: "30",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "2eccd04e-e85c-402e-8c3a-80686e9ec217",
    name: "Extendable Baton",
    category: meleeWeaponTypeEnum.Club,
    type: weaponTypeEnum.Melee,
    spec: "Batons",
    conceal: "0",
    accuracy: "5",
    reach: "1",
    damage: "(STR+2)P",
    armourPenetration: "-",

    availability: "4",
    cost: "100",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "94c29c4b-e4f4-493f-9155-447608e00874",
    name: "Nemesis Arms Maul Stun Staff",
    category: meleeWeaponTypeEnum.Club,
    type: weaponTypeEnum.Melee,
    conceal: "10",
    accuracy: "6",
    reach: "2",
    damage: "9S(e)",
    armourPenetration: "-5",

    availability: "8R",
    cost: "1000",
    allowaccessory: true,
    source: "RG",
    page: "20",
  },
  {
    id: "e6d9f23b-f4a4-4ba8-86ea-b3811f87fc82",
    name: "Sap",
    category: meleeWeaponTypeEnum.Club,
    type: weaponTypeEnum.Melee,
    spec: "Saps",
    conceal: "0",
    accuracy: "5",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-",

    availability: "2",
    cost: "30",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "73c71350-fafe-4f9e-af22-198727241a4d",
    name: "Staff",
    category: meleeWeaponTypeEnum.Club,
    type: weaponTypeEnum.Melee,
    spec: "Staves",
    conceal: "10",
    accuracy: "6",
    reach: "2",
    damage: "(STR+3)P",
    armourPenetration: "-",

    availability: "3",
    cost: "100",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "c0011883-a35b-4d32-94fd-dbb21e25882f",
    name: "Stun Baton",
    category: meleeWeaponTypeEnum.Club,
    type: weaponTypeEnum.Melee,
    spec: "Batons",
    conceal: "2",
    accuracy: "4",
    reach: "1",
    damage: "9S(e)",
    armourPenetration: "-5",
    mode: "0",
    rc: "0",
    ammo: "10",
    requireammo: "false",
    availability: "6R",
    cost: "750",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "b4b3a872-1532-4477-9bf3-76db34dc7bbf",
    name: "Telescoping Staff",
    category: meleeWeaponTypeEnum.Club,
    type: weaponTypeEnum.Melee,
    spec: "Staves",
    conceal: "0",
    accuracy: "4",
    reach: "2",
    damage: "(STR+2)P",
    armourPenetration: "-",

    availability: "4",
    cost: "350",
    allowaccessory: true,
    source: "SR5",
    page: "422",
  },
  {
    id: "a47e8191-869a-456e-b376-ed04ba7a59f0",
    name: "Ballistic Shield",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    spec: "Shields",
    conceal: "8",
    accuracy: "4",
    reach: "0",
    damage: "(STR+2)S",
    armourPenetration: "0",

    availability: "12R",
    cost: "1200",
    allowaccessory: true,
    source: "SR5",
    page: "438",
  },
  {
    id: "1752def7-cfed-44d8-a79f-bc95f32c4c13",
    name: "Battering Ram, Fluid-Motion",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    spec: "Battering Ram",
    conceal: "8",
    accuracy: "4",
    reach: "0",
    damage: "(STR+3)P",
    armourPenetration: "-1",

    availability: "10R",
    cost: "3500",
    allowaccessory: true,
    source: "RG",
    page: "103",
  },
  {
    id: "375930d0-6a29-480e-a6d8-46fe4eaf2a16",
    name: "Battering Ram, Pneumatic",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    spec: "Battering Ram",
    conceal: "8",
    accuracy: "4",
    reach: "0",
    damage: "16P",
    armourPenetration: "-4",

    availability: "18R",
    cost: "10000",
    allowaccessory: true,
    source: "RG",
    page: "104",
  },
  {
    id: "c0e77aad-3ecb-4136-b39d-00e9db6e6407",
    name: "Battering Ram, Shock",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    spec: "Battering Ram",
    conceal: "8",
    accuracy: "4",
    reach: "1",
    damage: "(STR+2)P + 12(e)",
    armourPenetration: "-3",

    availability: "10R",
    cost: "15000",
    allowaccessory: true,
    source: "RG",
    page: "104",
  },
  {
    id: "5ed720a1-bfa5-4670-85a2-5867f5caafbf",
    name: "Battering Ram, Standard",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    spec: "Battering Ram",
    conceal: "8",
    accuracy: "4",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-1",

    availability: "10R",
    cost: "2000",
    allowaccessory: true,
    source: "RG",
    page: "103",
  },
  {
    id: "ebbdbe5e-17da-4a97-8a65-9839513c91fe",
    name: "Blast Shield",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    spec: "Shield",
    conceal: "8",
    accuracy: "4",
    reach: "0",
    damage: "20P",
    armourPenetration: "-4",

    availability: "8R",
    cost: "20000",
    allowaccessory: true,
    source: "RG",
    page: "104",
  },
  {
    id: "fb814f8e-7284-4ae8-b362-63958d6a1921",
    name: "Monofilament Chainsaw",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    spec: "Chainsaw",
    conceal: "8",
    accuracy: "3",
    reach: "1",
    damage: "8P",
    armourPenetration: "-6",

    availability: "8",
    cost: "500",
    allowaccessory: true,
    source: "SR5",
    page: "448",
  },
  {
    id: "e66ab7ea-3408-4a3b-9ab9-7bc26a8e8a6e",
    name: "Riot Shield",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    spec: "Shields",
    conceal: "8",
    accuracy: "4",
    reach: "0",
    damage: "9S(e)",
    armourPenetration: "0",

    availability: "10R",
    cost: "1500",
    allowaccessory: true,
    source: "SR5",
    page: "438",
  },
  {
    id: "c0f77a8a-6bda-489e-aea6-bd4d6b3efe33",
    name: "Ash Arms Combat Chainsaw",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    conceal: "8",
    accuracy: "5",
    reach: "1",
    damage: "8P",
    armourPenetration: "-4",

    availability: "6R",
    cost: "2000",
    allowaccessory: true,
    source: "RG",
    page: "21",
  },
  {
    id: "05313081-d711-4af0-9a11-ebfbcdd4583f",
    name: "Ash Arms Monofilament Chainsaw",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    conceal: "8",
    accuracy: "5",
    reach: "1",
    damage: "12P",
    armourPenetration: "-8",

    availability: "8R",
    cost: "7500",
    allowaccessory: true,
    source: "RG",
    page: "21",
  },
  {
    id: "e3f90df3-a19e-458a-a09f-01ee4cd04502",
    name: "Bullwhip",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    conceal: "2",
    accuracy: "6",
    reach: "2",
    damage: "(STR+1)P",
    armourPenetration: "+3",

    availability: "6",
    cost: "100",
    allowaccessory: true,
    source: "RG",
    page: "20",
  },
  {
    id: "e9e5f7a1-a17f-4331-843d-c257af2130aa",
    name: "Garrote",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    conceal: "-4",
    accuracy: "5",
    reach: "0",
    damage: "(STR+4)S",
    armourPenetration: "-6",

    availability: "0",
    cost: "50",
    allowaccessory: true,
    source: "RG",
    page: "20",
  },
  {
    id: "f2ac00fc-305c-4f2e-b48d-62f9daa528c7",
    name: "Monofilament Garrote",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    conceal: "-4",
    accuracy: "5",
    reach: "0",
    damage: "(STR+6)P",
    armourPenetration: "-8",

    availability: "18F",
    cost: "2000",
    allowaccessory: true,
    source: "RG",
    page: "20",
  },
  {
    id: "c3ea1ed4-b117-4ba7-99eb-7d7b4b130b55",
    name: "Monofilament Whip",
    category: meleeWeaponTypeEnum.Exotic,
    type: weaponTypeEnum.Melee,
    conceal: "-4",
    accuracy: "5",
    reach: "2",
    damage: "12P",
    armourPenetration: "-8",

    availability: "12F",
    cost: "10000",
    allowaccessory: true,
    source: "SR5",
    page: "423",
  },
  {
    id: "07ce89c6-7c69-45a4-91a9-3375847c878a",
    name: "Bottle (broken, after first hit)",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "-4",
    accuracy: "3",
    reach: "0",
    damage: "(STR)P",
    armourPenetration: "0",

    availability: "0",
    allowaccessory: false,
    cost: "0",
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "4c1d521e-bc16-4b6f-9f54-f92e8f957ef4",
    name: "Bottle (unbroken)",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "-4",
    accuracy: "3",
    reach: "0",
    damage: "(STR+1)S",
    armourPenetration: "0",

    availability: "0",
    cost: "0",
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "0e43cd31-af94-44aa-9916-bddd579e602e",
    name: "Chain",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "2",
    accuracy: "4",
    reach: "2",
    damage: "(STR+1)P",
    armourPenetration: "0",

    availability: "0",
    cost: "10",
    allowaccessory: true,
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "fe954a0e-2d54-4bd4-9ea2-f1fc2c5bac58",
    name: "Chair",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "10",
    accuracy: "3",
    reach: "2",
    damage: "(STR+2)S",
    armourPenetration: "0",

    availability: "0",
    cost: "30",
    allowaccessory: true,
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "a9d3f2e3-256b-4557-8c06-3821d9d9b370",
    name: "Fork",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "-4",
    accuracy: "4",
    reach: "0",
    damage: "(STR-1)P",
    armourPenetration: "+1",

    availability: "0",
    cost: "0",
    allowaccessory: true,
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "7b6f0b51-e218-4f67-9ca4-99cdf6990535",
    name: "Frying Pan",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "3",
    reach: "2",
    damage: "(STR+1)P",
    armourPenetration: "0",

    availability: "0",
    cost: "20",
    allowaccessory: true,
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "9442e7c1-01ca-4331-831e-9ad2209fceb1",
    name: "Hammer",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "-2",
    accuracy: "4",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-1/-2",

    availability: "0",
    cost: "30",
    allowaccessory: true,
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "639651f0-a8bf-4884-ab73-0d78affa1a22",
    name: "Pistol",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "4",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "0",

    availability: "As weapon",
    cost: "As weapon",
    allowaccessory: true,
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "040a6dd5-e786-4196-8312-c1cb04505336",
    name: "Pool Cue",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "10",
    accuracy: "4",
    reach: "0",
    damage: "(STR)P",
    armourPenetration: "+1",

    availability: "0",
    cost: "45",
    allowaccessory: true,
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "9dfa8458-d544-4b31-924e-9439478d9d27",
    name: "Rifle Butt",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "6",
    accuracy: "3",
    reach: "0",
    damage: "(STR+3)S",
    armourPenetration: "0",

    availability: "As weapon",
    cost: "As weapon",
    allowaccessory: true,
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "6fc16aa4-f093-4677-a257-4649fd4280fa",
    name: "Sledge Hammer",
    category: meleeWeaponTypeEnum.Improvised,
    type: weaponTypeEnum.Melee,
    conceal: "10",
    accuracy: "3",
    reach: "1",
    damage: "(STR+4)P",
    armourPenetration: "0",

    availability: "1",
    cost: "40",
    allowaccessory: true,
    useskill: "Exotic Melee Weapon",
    source: "RG",
    page: "22",
  },
  {
    id: "168c2aa5-c4d9-4fd7-a629-fc70c6720d03",
    name: "Knucks",
    category: "Unarmed",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-",

    availability: "2R",
    cost: "100",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "SR5",
    page: "422",
  },
  {
    id: "e789ce47-f1bf-4c08-88b8-3295dddd03b1",
    name: "Shock Gloves",
    category: "Unarmed",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "8S(e)",
    armourPenetration: "-5",

    availability: "6R",
    cost: "550",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "SR5",
    page: "423",
  },
  {
    id: "fec4a4f8-4432-4bdc-b3b9-83c032d71d63",
    name: "Shock Hand",
    category: "Unarmed",
    type: weaponTypeEnum.Melee,
    spec: "Cyber Implants",
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "9S(e)",
    armourPenetration: "-5",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "SR5",
    page: "458",
  },
  {
    id: "63dcfdb6-bbd9-4a58-bbf4-cd35f7614fdc",
    name: "Unarmed Attack",
    category: "Unarmed",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR)S",
    armourPenetration: "-",

    availability: "0",
    cost: "0",
    allowaccessory: true,
    source: "SR5",
    page: "132",
  },
  {
    id: "793034c5-61b9-4a91-beea-eb7c671ee956",
    name: "Vibro Knife",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Knives",
    conceal: "-2",
    accuracy: "5",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-2",

    availability: "6R",
    cost: "1000",
    allowaccessory: true,
    source: "SASS",
    page: "31",
  },
  {
    id: "a5a300fd-d9fa-41dc-a792-2f96015cbe8a",
    name: "Vibro Sword",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "6",
    accuracy: "6",
    reach: "1",
    damage: "(STR+4)P",
    armourPenetration: "-2",

    availability: "8F",
    cost: "2000",
    allowaccessory: true,
    source: "SASS",
    page: "31",
  },
  {
    name: "Digging Claws",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR)P",
    armourPenetration: "+1",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "113",
  },
  {
    name: "Razor Claws",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-1",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "113",
  },
  {
    name: "Retractable Claws",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-1",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "113",
  },
  {
    id: "d8ce8d26-bccb-4107-aa90-3dd88af14d41",
    name: "Raptor Beak",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    reach: "-1",
    damage: "(STR+2)P",
    armourPenetration: "-2",

    conceal: "0",
    accuracy: "Physical",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "112",
  },
  {
    id: "847c2843-717f-4192-bad9-df21ffd4083b",
    name: "Fangs",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    reach: "-1",
    damage: "(STR+1)P",
    armourPenetration: "-",

    conceal: "0",
    accuracy: "Physical",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "115",
  },
  {
    id: "63bb72d2-977f-4ea3-b119-898186d2c299",
    name: "Functional Tail (Thagomizer)",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    reach: "1",
    damage: "(STR+3)P",
    armourPenetration: "-1",

    conceal: "0",
    accuracy: "Physical",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Exotic Melee Weapon",
    source: "RF",
    page: "115",
  },
  {
    id: "c847a859-8a72-4a1b-acb5-201ddc66fe73",
    name: "Goring Horns",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-1",

    conceal: "0",
    accuracy: "Physical",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Exotic Melee Weapon",
    source: "RF",
    page: "115",
  },
  {
    id: "54048c9d-854e-41b5-b493-6aa863da8fbd",
    name: "Larger Tusks",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-",

    conceal: "0",
    accuracy: "Physical",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "115",
  },
  {
    id: "1cdc0732-eb63-42c4-b8f4-cdf0e2d7c67c",
    name: "Proboscis",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR-1)P",
    armourPenetration: "+1",

    conceal: "0",
    accuracy: "Physical",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "118",
  },
  {
    id: "e4124dde-69f2-4322-884a-620ba7792b82",
    name: "Kick (Centaur)",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "1",
    damage: "(STR+2)P",
    armourPenetration: "+1",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "105",
  },
  {
    id: "e9dd389a-df19-4b1f-981f-342d23f2e506",
    name: "Bite (Infected)",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "-1",
    damage: "(STR+1)P",
    armourPenetration: "-1",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "137",
  },
  {
    id: "e9dd389a-df19-4b1f-981f-342d23f2e506",
    name: "Bite (Naga)",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "-1",
    damage: "(STR+1)P",
    armourPenetration: "-2",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "105",
  },
  {
    id: "30e8dab2-f435-4169-be3c-7e53a7840010",
    name: "Claws (Sasquatch)",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "1",
    damage: "(STR+1)P",
    armourPenetration: "0",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "105",
  },
  {
    id: "30e8dab2-f435-4169-be3c-7e53a7840010",
    name: "Claws (Infected) 3",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "1",
    damage: "(STR+3)P",
    armourPenetration: "-2",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "136",
  },
  {
    id: "30e8dab2-f435-4169-be3c-7e53a7840010",
    name: "Claws (Infected) 2",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "1",
    damage: "(STR+2)P",
    armourPenetration: "-1",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "136",
  },
  {
    id: "30e8dab2-f435-4169-be3c-7e53a7840010",
    name: "Claws (Infected) 1",
    category: "Natural",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "1",
    damage: "(STR+1)P",
    armourPenetration: "-1",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "136",
  },
  {
    id: "e9dd389a-df19-4b1f-981f-342d23f2e506",
    name: "Bite (Infected) 1",
    category: "Natural",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "-1",
    damage: "(STR+1)P",
    armourPenetration: "-1",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "137",
  },
  {
    id: "e9dd389a-df19-4b1f-981f-342d23f2e506",
    name: "Bite (Infected) 2",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "-1",
    damage: "(STR+2)P",
    armourPenetration: "-2",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "137",
  },
  {
    id: "e9dd389a-df19-4b1f-981f-342d23f2e506",
    name: "Bite (Gnawer)",
    category: "Quality",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "-1",
    damage: "(STR+2)P",
    armourPenetration: "-2",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "RF",
    page: "137",
  },
  {
    id: "0b43e7a8-892d-403a-a0e2-0d015556b1af",
    name: "Oral Slasher",
    category: "Cyberweapon",
    type: weaponTypeEnum.Melee,
    conceal: "-4",
    accuracy: "Physical",
    reach: "1",
    damage: "6P",
    armourPenetration: "-3",
    mode: "0",
    rc: "0",
    useskill: "Exotic Melee Weapon",
    ammo: "0",
    availability: "12R",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    source: "CF",
    page: "92",
  },
  {
    id: "8a842089-5a2c-43ee-9613-7f3db793fa71",
    name: "Cyberfangs",
    category: "Cyberweapon",
    type: weaponTypeEnum.Melee,
    conceal: "-4",
    accuracy: "Physical-2",
    reach: "0",
    damage: "(STR)P",
    armourPenetration: "0",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    useskill: "Unarmed Combat",
    allowaccessory: true,
    source: "CF",
    page: "91",
  },
  {
    id: "D82CFA4C-DBEB-4CEA-977C-8849E97C0438",
    name: "Extreme Cyberimplant",
    category: "Cyberweapon",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+5)P",
    armourPenetration: "0",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "91",
  },
  {
    id: "D82CFA4C-DBEB-4CEA-977C-8849E97C0438",
    name: "Junkyard Jaw",
    category: "Cyberweapon",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    useskill: "Unarmed Combat",
    damage: "(STR+3)P",
    armourPenetration: "-6",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    source: "CF",
    page: "91",
  },
  {
    name: "Claws (Bio-Weapon)",
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-3",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Retractable Claws (Bio-Weapon)",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-3",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Electrical Discharge",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "1-8S(e) (Special)",
    armourPenetration: "-4",

    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "122",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Fangs (Bio-Weapon)",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-4",

    conceal: "0",
    accuracy: "3",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "576770af-b5da-4b76-afdf-5559e7401e2d",
    name: "Retractable Fangs (Bio-Weapon)",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-4",

    conceal: "0",
    accuracy: "3",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Horns (Bio-Weapon)",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-4",

    conceal: "0",
    accuracy: "4",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Large Stinger",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    reach: "1",
    damage: "(STR+3)P",
    armourPenetration: "-4",

    conceal: "0",
    accuracy: "Physical",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Medium Stinger",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    reach: "1",
    damage: "(STR+2)P",
    armourPenetration: "-2",

    conceal: "0",
    accuracy: "Physical",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Horns (Bio-Weapon)",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-2",

    conceal: "0",
    accuracy: "4",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Medium Tusk(s)",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR)P",
    armourPenetration: "-1",

    conceal: "0",
    accuracy: "4",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Large Tusk(s)",
    category: "Bio-Weapon",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-2",

    conceal: "0",
    accuracy: "4",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "121",
  },
  {
    id: "458A2ECB-725D-414B-B033-23C18C62E61B",
    name: "Raptor Foot",
    category: "Cyber-Weapon",
    type: weaponTypeEnum.Melee,
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-3",

    conceal: "0",
    accuracy: "Physical-1",
    availability: "0",
    cost: "0",
    allowaccessory: false,
    useskill: "Unarmed Combat",
    source: "CF",
    page: "90",
  },
  {
    id: "a68d164d-4b79-47b9-ac89-4985ae18e882",
    name: "Sapphire Knife",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Knives",
    conceal: "-2",
    accuracy: "5",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "-3",

    availability: "6R",
    cost: "900",
    allowaccessory: true,
    source: "HT",
    page: "179",
  },
  {
    id: "cbc5270f-5848-41cd-a723-e86a7f48cfb4",
    name: "Ceramic/Plasteel Knife",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Knives",
    conceal: "-2",
    accuracy: "5",
    reach: "0",
    damage: "(STR+1)P",
    armourPenetration: "-1",

    availability: "4",
    cost: "75",
    allowaccessory: true,
    source: "HT",
    page: "179",
  },
  {
    id: "d036885b-4238-4ed7-ae9d-5dba97071e19",
    name: "Foot Blade",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Cyber Implants",
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "0",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "HT",
    page: "185",
  },
  {
    id: "7b928bc3-c44e-4002-b8ac-17a2bdd01d5a",
    name: "Bone Spike I",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Cyber Implants",
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+2)P",
    armourPenetration: "0",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "HT",
    page: "185",
  },
  {
    id: "2ef46f42-8890-48fd-bb94-67c34c12f0fb",
    name: "Bone Spike II",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Cyber Implants",
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+3)P",
    armourPenetration: "0",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "HT",
    page: "185",
  },
  {
    id: "3babb9d3-a3bb-4c8f-96ce-73f27b6ec7a6",
    name: "Bone Spike III",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Cyber Implants",
    conceal: "0",
    accuracy: "Physical",
    reach: "0",
    damage: "(STR+4)P",
    armourPenetration: "0",

    availability: "0",
    cost: "0",
    cyberware: "yes",
    allowaccessory: true,
    useskill: "Unarmed Combat",
    source: "HT",
    page: "185",
  },
  {
    id: "9434fb76-1d7f-463e-b377-b7c07e2a18e2",
    name: "Cougar Collapsible Spear",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "4",
    accuracy: "5",
    reach: "3",
    damage: "(STR+3)P",
    armourPenetration: "-2",

    availability: "14R",
    cost: "1250",
    allowaccessory: true,
    source: "HT",
    page: "180",
  },
  {
    id: "6967eea2-01f8-4931-a59f-d2cd64419561",
    name: "Collapsible Scythe",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "4",
    accuracy: "5",
    reach: "2",
    damage: "(STR+2)P",
    armourPenetration: "-2",

    availability: "16R",
    cost: "2350",
    allowaccessory: true,
    source: "HT",
    page: "183",
  },
  {
    id: "023bb6db-4c14-470b-a063-9df1adf31a00",
    name: "Victorinox Collapsible Hatchet",
    category: meleeWeaponTypeEnum.Blade,
    type: weaponTypeEnum.Melee,
    spec: "Swords",
    conceal: "4",
    accuracy: "5",
    reach: "1",
    damage: "(STR+2)P",
    armourPenetration: "-1",

    availability: "4",
    cost: "250",
    allowaccessory: true,
    source: "HT",
    page: "179",
  },
];

export const projectileWeaponsList: Array<
  RequiredEntityData<ProjectileWeapons>
> = [
  {
    name: "Bow",
    subtype: projectileWeaponTypeEnum.Bows,
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        calculationType: damageCalculationMethodEnum.Rating,
        base: 2,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: {
      base: "Calculation",
      specialCalculation: [
        -1,
        mathOperatorEnum.Multiply,
        "Rating",
        mathOperatorEnum.Divide,
        4,
      ],
    },
    availability: {
      rating: "Calculation",
      specialCalculation: ["Rating"],
      restriction: restrictionEnum.Legal,
    },
    rating: {
      maximum: 10,
    },
    cost: {
      base: "Calculation",
      specialCalculation: ["Rating", mathOperatorEnum.Multiply, 100],
    },
    description: "",
    relatedSkill: skillsEnum.Archery,
    type: weaponTypeEnum.Projectile,
  },
  {
    name: "Light Crossbow",
    subtype: projectileWeaponTypeEnum.Crossbows,
    accuracy: {
      base: 7,
    },
    damage: {
      damageAmount: {
        calculationType: damageCalculationMethodEnum.Normal,
        base: 5,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    availability: { rating: 2, restriction: restrictionEnum.Legal },
    cost: { base: 300 },
    description: "",
    relatedSkill: skillsEnum.Archery,
    type: weaponTypeEnum.Projectile,
  },
  {
    name: "Medium Crossbow",
    subtype: projectileWeaponTypeEnum.Crossbows,
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        calculationType: damageCalculationMethodEnum.Normal,
        base: 7,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -2 },
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 500 },
    description: "",
    relatedSkill: skillsEnum.Archery,
    type: weaponTypeEnum.Projectile,
  },
  {
    name: "Heavy Crossbow",
    subtype: projectileWeaponTypeEnum.Crossbows,
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        calculationType: damageCalculationMethodEnum.Normal,
        base: 10,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -3 },
    availability: { rating: 8, restriction: restrictionEnum.Restricted },
    cost: { base: 1000 },
    description: "",
    relatedSkill: skillsEnum.Archery,
    type: weaponTypeEnum.Projectile,
  },
  {
    name: "Throwing knifes/shuriken",
    subtype: projectileWeaponTypeEnum.ThrowingWeapons,
    accuracy: {
      base: "Inherent",
    },
    damage: {
      damageAmount: {
        calculationType: damageCalculationMethodEnum.Strength,
        base: 1,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 25 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.ThrowingWeapons,
    type: weaponTypeEnum.Projectile,
  },
];

export const firearmWeaponsList: Array<RequiredEntityData<FirearmWeapons>> = [
  {
    subtype: firearmWeaponTypeEnum.Tasers,
    name: "Defiance EX Shocker",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 9,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Stun,
      annotation: damageAnnoationEnum.Electrical,
    },
    armourPenetration: { base: -5 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 4,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 0, restriction: restrictionEnum.Legal },
    cost: { base: 250 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Tasers,
    name: "Defiance EX Shocker (Melee)",
    accuracy: {
      base: 3,
    },
    damage: {
      damageAmount: {
        base: 8,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Stun,
      annotation: damageAnnoationEnum.Electrical,
    },
    armourPenetration: { base: -5 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 4,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 0, restriction: restrictionEnum.Legal },
    cost: { base: 250 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.Clubs,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Tasers,
    name: "Yamaha Pulsar",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Stun,
      annotation: damageAnnoationEnum.Electrical,
    },
    armourPenetration: { base: -5 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 4,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 0, restriction: restrictionEnum.Legal },
    cost: { base: 180 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HoldOuts,
    name: "Fichetti Tiffani Needler",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 8,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
      annotation: damageAnnoationEnum.Flechette,
    },
    armourPenetration: { base: 5 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 4,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 5, restriction: restrictionEnum.Restricted },
    cost: { base: 1000 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HoldOuts,
    name: "Streetline Special",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 6,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 6,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 120 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HoldOuts,
    name: "Walther Palm Pistol",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 4,
        reloadMethod: reloadMethodEnum.MuzzleLoader,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 180 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightPistol,
    name: "Ares Light Fire 75",
    accuracy: {
      base: 6,
      equipment: 8,
    },
    damage: {
      damageAmount: {
        base: 6,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 16,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 6, restriction: restrictionEnum.Forbidden },
    cost: { base: 1250 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightPistol,
    name: "Ares Light Fire 70",
    accuracy: {
      base: 7,
    },
    damage: {
      damageAmount: {
        base: 6,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 16,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 3, restriction: restrictionEnum.Restricted },
    cost: { base: 200 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightPistol,
    name: "Beretta 201T",
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        base: 6,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 21,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 7, restriction: restrictionEnum.Restricted },
    cost: { base: 210 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightPistol,
    name: "Colt America L36",
    accuracy: {
      base: 7,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 11,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 320 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightPistol,
    name: "Fichetti Security 600",
    accuracy: {
      base: 6,
      equipment: 7,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 30,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 6, restriction: restrictionEnum.Restricted },
    cost: { base: 350 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightPistol,
    name: "Taurus Omni-6",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 6,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 6,
        reloadMethod: reloadMethodEnum.Cylinder,
      },
    ],
    availability: { rating: 3, restriction: restrictionEnum.Restricted },
    cost: { base: 300 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightPistol,
    name: "Taurus Omni-6 (with heavy pistol ammo)",
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 6,
        reloadMethod: reloadMethodEnum.Cylinder,
      },
    ],
    availability: { rating: 3, restriction: restrictionEnum.Restricted },
    cost: { base: 300 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HeavyPistol,
    name: "Ares Predator V",
    accuracy: {
      base: 5,
      equipment: 7,
    },
    damage: {
      damageAmount: {
        base: 8,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 15,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 5, restriction: restrictionEnum.Restricted },
    cost: { base: 725 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HeavyPistol,
    name: "Ares Viper Slivergun",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 9,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
      annotation: damageAnnoationEnum.Flechette,
    },
    armourPenetration: { base: 4 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 30,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 8, restriction: restrictionEnum.Forbidden },
    cost: { base: 380 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HeavyPistol,
    name: "Browning Ultra-Power",
    accuracy: {
      base: 5,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 8,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 10,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 640 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HeavyPistol,
    name: "Colt Government 2066",
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 14,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 7, restriction: restrictionEnum.Restricted },
    cost: { base: 425 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HeavyPistol,
    name: "Remington Roomsweeper",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 8,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 6, restriction: restrictionEnum.Restricted },
    cost: { base: 250 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HeavyPistol,
    name: "Remington Roomsweeper (with flechettes)",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 9,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      annotation: damageAnnoationEnum.Flechette,
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 4 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 8,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 6, restriction: restrictionEnum.Restricted },
    cost: { base: 250 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HeavyPistol,
    name: "Ruger Super Warhawk",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 9,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -2 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 6,
        reloadMethod: reloadMethodEnum.Cylinder,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 400 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.MachinePistol,
    name: "Ares Crusader II",
    accuracy: {
      base: 5,
      equipment: 7,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 2 },
    ammo: [
      {
        amount: 40,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 9, restriction: restrictionEnum.Restricted },
    cost: { base: 830 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.MachinePistol,
    name: "Ceska Black Scorpion",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 6,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 35,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 6, restriction: restrictionEnum.Restricted },
    cost: { base: 270 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.MachinePistol,
    name: "Steyr TMP",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [
      firearmModeEnum.SemiAutomatic,
      firearmModeEnum.BurstFire,
      firearmModeEnum.FullAutomatic,
    ],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 30,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 8, restriction: restrictionEnum.Restricted },
    cost: { base: 350 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SubmachineGun,
    name: "Colt Cobra TZ-120",
    accuracy: {
      base: 4,
      equipment: 5,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [
      firearmModeEnum.SemiAutomatic,
      firearmModeEnum.BurstFire,
      firearmModeEnum.FullAutomatic,
    ],
    recoilCompensation: { base: 2, equipment: 3 },
    ammo: [
      {
        amount: 32,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 5, restriction: restrictionEnum.Restricted },
    cost: { base: 660 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SubmachineGun,
    name: "FN P93 Praetor",
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        base: 8,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [
      firearmModeEnum.SemiAutomatic,
      firearmModeEnum.BurstFire,
      firearmModeEnum.FullAutomatic,
    ],
    recoilCompensation: { base: 1, equipment: 2 },
    ammo: [
      {
        amount: 50,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 11, restriction: restrictionEnum.Forbidden },
    cost: { base: 900 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SubmachineGun,
    name: "HK-227",
    accuracy: {
      base: 5,
      equipment: 7,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [
      firearmModeEnum.SemiAutomatic,
      firearmModeEnum.BurstFire,
      firearmModeEnum.FullAutomatic,
    ],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 28,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 8, restriction: restrictionEnum.Restricted },
    cost: { base: 730 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SubmachineGun,
    name: "Ingram Smartgun X",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 8,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.BurstFire, firearmModeEnum.FullAutomatic],
    recoilCompensation: { base: 2 },
    ammo: [
      {
        amount: 32,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 6, restriction: restrictionEnum.Restricted },
    cost: { base: 800 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SubmachineGun,
    name: "SCK Model 100",
    accuracy: {
      base: 5,
      equipment: 7,
    },
    damage: {
      damageAmount: {
        base: 8,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 30,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 6, restriction: restrictionEnum.Restricted },
    cost: { base: 8875 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SubmachineGun,
    name: "Uzi IV",
    accuracy: {
      base: 4,
      equipment: 5,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.BurstFire],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 24,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 450 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultRifle,
    name: "AK-97",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 10,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -2 },
    mode: [
      firearmModeEnum.SemiAutomatic,
      firearmModeEnum.BurstFire,
      firearmModeEnum.FullAutomatic,
    ],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 38,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 950 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultRifle,
    name: "Ares Alpha",
    accuracy: {
      base: 5,
      equipment: 7,
    },
    damage: {
      damageAmount: {
        base: 11,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -2 },
    mode: [
      firearmModeEnum.SemiAutomatic,
      firearmModeEnum.BurstFire,
      firearmModeEnum.FullAutomatic,
    ],
    recoilCompensation: { base: 2 },
    ammo: [
      {
        amount: 42,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 11, restriction: restrictionEnum.Forbidden },
    cost: { base: 2650 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultRifle,
    name: "Ares Alpha (Grenade Launcher)",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Grenade,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -2 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 6,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 11, restriction: restrictionEnum.Forbidden },
    cost: { base: 2650 },
    description: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultRifle,
    name: "Colt M23",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 9,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -2 },
    mode: [
      firearmModeEnum.SemiAutomatic,
      firearmModeEnum.BurstFire,
      firearmModeEnum.FullAutomatic,
    ],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 40,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 550 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultRifle,
    name: "FN HAR",
    accuracy: {
      base: 5,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 10,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -2 },
    mode: [
      firearmModeEnum.SemiAutomatic,
      firearmModeEnum.BurstFire,
      firearmModeEnum.FullAutomatic,
    ],
    recoilCompensation: { base: 2 },
    ammo: [
      {
        amount: 35,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 8, restriction: restrictionEnum.Restricted },
    cost: { base: 1500 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultRifle,
    name: "Yamaha Raiden",
    accuracy: {
      base: 6,
      equipment: 8,
    },
    damage: {
      damageAmount: {
        base: 11,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -2 },
    mode: [firearmModeEnum.BurstFire, firearmModeEnum.FullAutomatic],
    recoilCompensation: { base: 1 },
    ammo: [
      {
        amount: 60,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 14, restriction: restrictionEnum.Forbidden },
    cost: { base: 2600 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SniperRifle,
    name: "Ares Desert Strike",
    accuracy: {
      base: 7,
    },
    damage: {
      damageAmount: {
        base: 12,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -4 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 14,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 10, restriction: restrictionEnum.Forbidden },
    cost: { base: 17500 },
    description: "",
    relatedSkill: skillsEnum.Longarms,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SniperRifle,
    name: "Cavalier Arms Crockett EBR",
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        base: 12,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -3 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 20,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 12, restriction: restrictionEnum.Forbidden },
    cost: { base: 10300 },
    description: "",
    relatedSkill: skillsEnum.Longarms,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SniperRifle,
    name: "Ranger Arms SM-5",
    accuracy: {
      base: 8,
    },
    damage: {
      damageAmount: {
        base: 14,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -5 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 15,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 16, restriction: restrictionEnum.Forbidden },
    cost: { base: 28000 },
    description: "",
    relatedSkill: skillsEnum.Longarms,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SniperRifle,
    name: "Remington 950",
    accuracy: {
      base: 7,
    },
    damage: {
      damageAmount: {
        base: 12,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -4 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 5,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 2100 },
    description: "",
    relatedSkill: skillsEnum.Longarms,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SniperRifle,
    name: "Ruger 100",
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        base: 11,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -3 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 8,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 1300 },
    description: "",
    relatedSkill: skillsEnum.Longarms,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Shotgun,
    name: "Defiance T-250",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 10,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SingleShot, firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 5,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 450 },
    description: "",
    relatedSkill: skillsEnum.Longarms,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Shotgun,
    name: "Enfield AS-7",
    accuracy: {
      base: 4,
      equipment: 5,
    },
    damage: {
      damageAmount: {
        base: 13,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 10,
        reloadMethod: reloadMethodEnum.Cylinder,
      },
      { amount: 24, reloadMethod: reloadMethodEnum.Drum },
    ],
    availability: { rating: 12, restriction: restrictionEnum.Forbidden },
    cost: { base: 1100 },
    description: "",
    relatedSkill: skillsEnum.Longarms,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Shotgun,
    name: "PJSS Model 55",
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        base: 11,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 2,
        reloadMethod: reloadMethodEnum.BreakAction,
      },
    ],
    availability: { rating: 9, restriction: restrictionEnum.Restricted },
    cost: { base: 1000 },
    description: "",
    relatedSkill: skillsEnum.Longarms,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Special,
    name: "Ares S-III Super Squirt",
    accuracy: {
      base: 3,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Chemical,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 20,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 7, restriction: restrictionEnum.Restricted },
    cost: { base: 950 },
    description: "",
    relatedSkill: skillsEnum.ExoticRangedWeapon,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Special,
    name: "Fichetti Pain Inducer",
    accuracy: {
      base: 3,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Chemical,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 10,
        reloadMethod: reloadMethodEnum.Special,
      },
    ],
    availability: { rating: 11, restriction: restrictionEnum.Restricted },
    cost: { base: 5000 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.ExoticRangedWeapon,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Special,
    name: "Parashield Dart Pistol",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.DrugToxin,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 5,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 4, restriction: restrictionEnum.Restricted },
    cost: { base: 600 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.ExoticRangedWeapon,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Special,
    name: "Parashield Dart Rifle",
    accuracy: {
      base: 6,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.DrugToxin,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 6,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 6, restriction: restrictionEnum.Restricted },
    cost: { base: 1200 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.ExoticRangedWeapon,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Special,
    name: "Micro flare launcher",
    accuracy: {
      base: 3,
    },
    damage: {
      damageAmount: {
        base: 5,
        calculationType: damageCalculationMethodEnum.Fire,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -5 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 1,
        reloadMethod: reloadMethodEnum.MuzzleLoader,
      },
    ],
    availability: { rating: 0, restriction: restrictionEnum.Legal },
    cost: { base: 175 },
    description: "",
    relatedSkill: skillsEnum.ExoticRangedWeapon,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Special,
    name: "Grapple gun",
    accuracy: {
      base: 3,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Stun,
    },
    armourPenetration: { base: -2 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 1,
        reloadMethod: reloadMethodEnum.MuzzleLoader,
      },
    ],
    availability: { rating: 8, restriction: restrictionEnum.Restricted },
    cost: { base: 500 },
    description: "",
    relatedSkill: skillsEnum.ExoticRangedWeapon,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightMachinegun,
    name: "Ingram Valiant",
    accuracy: {
      base: 5,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 9,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -2 },
    mode: [firearmModeEnum.BurstFire, firearmModeEnum.FullAutomatic],
    recoilCompensation: { base: 2, equipment: 3 },
    ammo: [
      {
        amount: 50,
        reloadMethod: reloadMethodEnum.Clip,
      },
      {
        amount: 100,
        reloadMethod: reloadMethodEnum.BeltFed,
      },
    ],
    availability: { rating: 12, restriction: restrictionEnum.Forbidden },
    cost: { base: 5800 },
    description: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.MediumHeavyMachinegun,
    name: "Stoner-Ares M202",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 10,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -3 },
    mode: [firearmModeEnum.FullAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 50,
        reloadMethod: reloadMethodEnum.Clip,
      },
      {
        amount: 100,
        reloadMethod: reloadMethodEnum.BeltFed,
      },
    ],
    availability: { rating: 12, restriction: restrictionEnum.Forbidden },
    cost: { base: 7000 },
    description: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.MediumHeavyMachinegun,
    name: "RPK HMG",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 12,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -4 },
    mode: [firearmModeEnum.FullAutomatic],
    recoilCompensation: { base: 0, equipment: 6 },
    ammo: [
      {
        amount: 50,
        reloadMethod: reloadMethodEnum.Clip,
      },
      {
        amount: 100,
        reloadMethod: reloadMethodEnum.BeltFed,
      },
    ],
    availability: { rating: 16, restriction: restrictionEnum.Forbidden },
    cost: { base: 16300 },
    description: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultCannon,
    name: "Ares Antioch-2",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Grenade,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 8,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 8, restriction: restrictionEnum.Forbidden },
    cost: { base: 3200 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultCannon,
    name: "ArmTech MGL-12",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Grenade,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 12,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 10, restriction: restrictionEnum.Forbidden },
    cost: { base: 5000 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultCannon,
    name: "Aztechnology Striker",
    accuracy: {
      base: 5,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Missile,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 1,
        reloadMethod: reloadMethodEnum.MuzzleLoader,
      },
    ],
    availability: { rating: 10, restriction: restrictionEnum.Forbidden },
    cost: { base: 1200 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultCannon,
    name: "Krime Cannon",
    accuracy: {
      base: 4,
    },
    damage: {
      damageAmount: {
        base: 16,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -6 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0, equipment: 1 },
    ammo: [
      {
        amount: 6,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
    ],
    availability: { rating: 20, restriction: restrictionEnum.Forbidden },
    cost: { base: 21000 },
    description: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultCannon,
    name: "Onotari Interceptor",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Missile,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 2,
        reloadMethod: reloadMethodEnum.MuzzleLoader,
      },
    ],
    availability: { rating: 18, restriction: restrictionEnum.Forbidden },
    cost: { base: 14000 },
    description: "",
    wireless: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultCannon,
    name: "Panther XXL",
    accuracy: {
      base: 5,
      equipment: 7,
    },
    damage: {
      damageAmount: {
        base: 17,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -6 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 15,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: { rating: 20, restriction: restrictionEnum.Forbidden },
    cost: { base: 43000 },
    description: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HoldOuts,
    name: "Cyber Hold-out pistol",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 6,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 2,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
      {
        amount: 6,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: {
      rating: 8,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 2000 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightPistol,
    name: "Cyber light pistol",
    accuracy: {
      base: 6,
      equipment: 8,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 10,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
      {
        amount: 15,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: {
      rating: 10,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 3900 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.LightPistol,
    name: "Cyber machine pistol",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 6,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 1 },
    ammo: [
      {
        amount: 18,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
      {
        amount: 32,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: {
      rating: 12,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 3500 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.HeavyPistol,
    name: "Cyber heavy pistol",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SemiAutomatic],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 4,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
      {
        amount: 10,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: {
      rating: 12,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 4300 },
    description: "",
    relatedSkill: skillsEnum.Pistols,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.SubmachineGun,
    name: "Cyber submachine gun",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 7,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SemiAutomatic, firearmModeEnum.BurstFire],
    recoilCompensation: { base: 2 },
    ammo: [
      {
        amount: 18,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
      {
        amount: 32,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: {
      rating: 12,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 4800 },
    description: "",
    relatedSkill: skillsEnum.Automatics,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.Shotgun,
    name: "Cyber shotgun",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 10,
        calculationType: damageCalculationMethodEnum.Normal,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: -1 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 4,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
      {
        amount: 10,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: {
      rating: 12,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 8500 },
    description: "",
    relatedSkill: skillsEnum.Longarms,
    type: weaponTypeEnum.Firearm,
  },
  {
    subtype: firearmWeaponTypeEnum.AssaultCannon,
    name: "Cyber microgrenade launcher",
    accuracy: {
      base: 4,
      equipment: 6,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Grenade,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    mode: [firearmModeEnum.SingleShot],
    recoilCompensation: { base: 0 },
    ammo: [
      {
        amount: 2,
        reloadMethod: reloadMethodEnum.InternalMagazine,
      },
      {
        amount: 6,
        reloadMethod: reloadMethodEnum.Clip,
      },
    ],
    availability: {
      rating: 20,
      restriction: restrictionEnum.Restricted,
    },
    cost: { base: 30000 },
    description: "",
    relatedSkill: skillsEnum.HeavyWeapons,
    type: weaponTypeEnum.Firearm,
  },
];

export const explosivesList: Array<RequiredEntityData<Explosives>> = [
  {
    subtype: explosiveTypeEnum.Standard,
    name: "Commercial explosives",
    accuracy: {
      base: 0,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Explosive,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    availability: { rating: 8, restriction: restrictionEnum.Restricted },
    rating: {
      minimum: 5,
      maximum: 5,
    },
    cost: { base: 100 },
    description: "",
    relatedSkill: skillsEnum.Demolitions,
    type: weaponTypeEnum.Explosive,
  },
  {
    subtype: explosiveTypeEnum.Standard,
    name: "Explosive Foam",
    accuracy: {
      base: 0,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Explosive,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    availability: { rating: 12, restriction: restrictionEnum.Forbidden },
    rating: {
      minimum: 6,
      maximum: 25,
    },
    cost: {
      base: "Calculation",
      specialCalculation: ["Rating", mathOperatorEnum.Multiply, 100],
    },
    description: "",
    relatedSkill: skillsEnum.Demolitions,
    type: weaponTypeEnum.Explosive,
  },
  {
    subtype: explosiveTypeEnum.Standard,
    name: "Plastic explosives",
    accuracy: {
      base: 0,
    },
    damage: {
      damageAmount: {
        base: 0,
        calculationType: damageCalculationMethodEnum.Explosive,
      },
      type: damageTypeEnum.Physical,
    },
    armourPenetration: { base: 0 },
    availability: { rating: 16, restriction: restrictionEnum.Forbidden },
    rating: {
      minimum: 6,
      maximum: 25,
    },
    cost: {
      base: "Calculation",
      specialCalculation: ["Rating", mathOperatorEnum.Multiply, 100],
    },
    description: "",
    relatedSkill: skillsEnum.Demolitions,
    type: weaponTypeEnum.Explosive,
  },
];
